<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Small</formFactors>
    <formFactors>Medium</formFactors>
    <formFactors>Large</formFactors>
    <navType>Standard</navType>
    <tab>standard-home</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Task</tab>
    <tab>standard-File</tab>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Campaign</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-report</tab>
    <tab>standard-Feed</tab>
    <tab>standard-CollaborationGroup</tab>
    <tab>standard-Event</tab>
    <tab>standard-OtherUserProfile</tab>
    <tab>standard-Case</tab>
    <tab>standard-News</tab>
    <tab>standard-Forecasting3</tab>
    <tab>All_Scheduled_Jobs__c</tab>
    <tab>Apex_Job_Runner</tab>
    <tab>Sample</tab>
    <tab>ZTS_US_Event_Account__c</tab>
    <tab>Account_Info__c</tab>
    <tab>Transaction_History__c</tab>
    <tab>Loan__c</tab>
    <tab>Credit_History__c</tab>
    <uiType>Lightning</uiType>
</CustomApplication>
