public class Constants{
    public static String CONST_TWELVE_AM = '12:00 AM';
    public static String CONST_ONE_AM = '1:00 AM';
    public static String CONST_TWO_AM = '2:00 AM';
    public static String CONST_THREE_AM = '3:00 AM';
    public static String CONST_FOUR_AM = '4:00 AM';
    public static String CONST_FIVE_AM = '5:00 AM';
    public static String CONST_SIX_AM = '6:00 AM';
    public static String CONST_SEVEN_AM = '7:00 AM';
    public static String CONST_EIGHT_AM = '8:00 AM';
    public static String CONST_NINE_AM = '9:00 AM';
    public static String CONST_TEN_AM = '10:00 AM';
    public static String CONST_ELEVEN_AM = '11:00 AM';
    public static String CONST_TWELVE_PM = '12:00 PM';
    public static String CONST_ONE_PM = '1:00 PM';
    public static String CONST_TWO_PM = '2:00 PM';
    public static String CONST_THREE_PM = '3:00 PM';
    public static String CONST_FOUR_PM = '4:00 PM';
    public static String CONST_FIVE_PM = '5:00 PM';
    public static String CONST_SIX_PM = '6:00 PM';
    public static String CONST_SEVEN_PM = '7:00 PM';
    public static String CONST_EIGHT_PM = '8:00 PM';
    public static String CONST_NINE_PM = '9:00 PM';
    public static String CONST_TEN_PM = '10:00 PM';
    public static String CONST_ELEVEN_PM = '11:00 PM';
    
    public static String CONST_SUNDAY = 'Sunday';
    public static String CONST_MONDAY = 'Monday';
    public static String CONST_TUESDAY = 'Tuesday';
    public static String CONST_WEDNESDAY = 'Wednesday';
    public static String CONST_THURSDAY = 'Thursday';
    public static String CONST_FRIDAY = 'Friday';
    public static String CONST_SATURDAY = 'Saturday';
   
}